### ISSUE TITLE
Work in progress

### ISSUE THREAD

**Issue by mariusor** [go-ap/activitypub#1]
Hi, 

The code is not yet in a state to be used in any real life scenarios. 

For now it's just a toy project, from a Go beginner, which tries to build a very basic API interface for the [Activity Pub](https://www.w3.org/TR/2017/CR-activitypub-20170907/) and [Activity Streams](https://www.w3.org/TR/activitystreams-core/) specifications. 

Incidentally, there's also a [json-ld](https://www.w3.org/TR/json-ld/) marshaling/unmarshaling API which tries to stay close to the `json.Marshaler` and `json.Unmarshaler` interfaces[1]. This might end up a bit  too specific to be of use in other contexts.

If you are in need of something that sounds a lot like this, please leave comments, suggestions or, even better, feature and/or pull requests.

[1] The existing packages (as far as I could find them) do not follow the `json.Marshal` documentation regarding [anonymous struct fields](https://golang.org/pkg/encoding/json/#Marshal) and they end up messing the structure.

**Comment by mariusor** [comment]
Currently this is no longer 100% true.

I have started using the library in one of my projects, see [littr.go](https://github.com/mariusor/littr.go) and I made steady progress towards having it not be too cumbersome to use.

However, I am still a go lang beginner, so the library makes no promises of memory safety, speed or not eating your dog.

**Comment by gedw99** [comment]
I started playing with another project that does the same thing.
It's much further along in the golang implementation of activity dtreams.

Do you know the one I mean ?

**Comment by gedw99** [comment]
That's the one

On top of http://go-fed.org/

**Comment by gedw99** [comment]
Maybe you have totally different goals though ? I want to build it around
content stores.

**Comment by mariusor** [comment]
At the time I started the work on this library go-fed didn't exist yet.

I keep in touch with its author on mastodon but yes, I think we have different goals in mind.

So far I'm working on this project to scratch my own itch, if it fails to do that it will probably get scraped in favour of something else that does it. :)

If you have the time to kill, you could add some tickets that would help with your particular use cases. I'm willing to work on them in the limit of available time even if it's just to get a mostly objective comparison between go-fed and activitypub.go.

**Comment by gedw99** [comment]
Understand.

Well I would work on integration of activity streams with a content store .
That's what I am working on using go-fed..

For example the excellent File Browser plugin for Caddy.
Why not work on that ?
Much more productive and you will learn golang better

**Comment by gedw99** [comment]
Found it

https://github.com/filebrowser

The code is very high quality so you learn much better patterns

**Comment by mariusor** [comment]
I think that maybe I can close this.

It's still not perfect, but we're getting closer to providing a decent API for applications that require vanilla activitypub functionality.
