### ISSUE TITLE
README.md incorrectly contrasts `OnXXX` funcs

### ISSUE THREAD

**Issue by johnsto** [go-ap/activitypub#12]
The readme appears to contain a mistake here, comparing regular `OnTXXX` to `[T]OnXXX` calls (respectively):

```
Before using them you should consider that the former comes with a pretty heavy performance penalty:
```

The benchmarks after this paragraph actually show it is the *latter*, generic `[T]OnXXX` that carry a significant performance penalty.

**Comment by mariusor** [comment]
It looks like I clarified the document a while back. Thank you for your feedback, and apologies for having this in limbo for so long. :)
