### ISSUE TITLE
Should type of 'Attachment' be 'ItemCollection'?

### ISSUE THREAD

**Issue by snoymy** [go-ap/activitypub#13]
Currently, the property `Attachement` in `Object` struct and some other struct has type `Item`. Since from the [Activitypub Vocabulary Spec (Example 66)](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-attachment) shown that `attachment` field can be JSON array, so shouldn't `Attachement` be type `ItemCollection`? Or I miss something?

__Activitypub Vocabulary Example 66__
```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Note",
  "name": "Have you seen my cat?",
  "attachment": [
    {
      "type": "Image",
      "content": "This is what he looks like.",
      "url": "http://example.org/cat.jpeg"
    }
  ]
}
```

__Ex. object.go__
```go
type Object struct {
        /* .... */

	// Attachment identifies a resource attached or related to an object that potentially requires special handling.
	// The intent is to provide a model that is at least semantically similar to attachments in email.
	Attachment Item `jsonld:"attachment,omitempty"`

       /* .... */
}
```

__Ex. actor.go__
```go
type Actor struct {
        /* .... */

	// Attachment identifies a resource attached or related to an object that potentially requires special handling.
	// The intent is to provide a model that is at least semantically similar to attachments in email.
	Attachment Item `jsonld:"attachment,omitempty"`

       /* .... */
}
```

**Comment by mariusor** [comment]
Hi @snoymy, sorry for the very late reply, but I rarely visit github. The preferred support channel for Go-ActivityPub is through [one](https://lists.sr.ht/~mariusor/go-activitypub-discuss) of its [mailing lists](https://lists.sr.ht/~mariusor/go-activitypub-dev).

Coming back to your question, the `Item` data type is an interface that is satisfied by the slice type `ItemCollection`, therefore the definition of the Attachment property is correct in using it, but you are also correct in assuming it can contain an `ItemCollection`, which is what usually happens. The json deserialization that we're using, can build the types that are represented dynamically, ie, if it's an array it creates a `ItemCollection` slice.

In this package the types that fulfill the `Item` interface are the distinct structs for each vanilla ActivityPub object (eg, `Activity`, `Object`, `Actor`, `Collection`), the `ItemCollection` type and the `IRI` stringy type.

I hope this helps.

**Comment by mariusor** [comment]
You can also have a look at this [longer explanation](https://man.sr.ht/~mariusor/go-activitypub/go-ap/index.md#design-decisions) for the reasoning behind the behaviour I mentioned above.
